[tool.pyright]
typeCheckingMode = "basic"
reportInvalidTypeForm = "none"
reportAssignmentType = "none"

[tool.ruff]
exclude = [
    "jakarto_layers_qgis/vendor/**",
    "jakarto_layers_qgis/ui/resources_rc.py"
]
target-version = "py39"

[tool.coverage.run]
source = ["jakarto_layers_qgis"]
omit = [
    "jakarto_layers_qgis/vendor/**",
    "jakarto_layers_qgis/ui/resources_rc.py",
    "tests/**"
]

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "def __repr__",
    "raise NotImplementedError",
    "if __name__ == .__main__.:",
    "pass",
    "raise ImportError"
]

[tool.vendoring]
destination = "jakarto_layers_qgis/vendor"
requirements = "requirements-vendor.txt"
namespace = "jakarto_layers_qgis.vendor"

patches-dir = "vendoring-patches"

[tool.vendoring.transformations]
drop = [
    "*.dist-info",
    "*.egg-info",
    "websockets/speedups*",
]
